MyNote/Models/Note.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyNote.Models
{
    public class Note
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(250)]
        public string Title { get; set; }

        [Required]
        public string Text { get; set; }

        public DateTime CreatedAt { get; set; }
    }
}

MyNote/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MyNote.Models;
using MyNote.Views.SaasEcom.ViewModels;
using SaasEcom.Core.DataServices.Storage;
using SaasEcom.Core.Infrastructure.Facades;
using SaasEcom.Core.Infrastructure.PaymentProcessor.Stripe;

namespace MyNote.Controllers
{
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        private SubscriptionsFacade _subscriptionsFacade;
        private SubscriptionsFacade SubscriptionsFacade
        {
            get
            {
                return _subscriptionsFacade ?? (_subscriptionsFacade = new SubscriptionsFacade(
                           new SubscriptionDataService<ApplicationDbContext, ApplicationUser>
                               (HttpContext.GetOwinContext().Get<ApplicationDbContext>()),
                           new SubscriptionProvider(ConfigurationManager.AppSettings["StripeApiSecretKey"]),
                           new CardProvider(ConfigurationManager.AppSettings["StripeApiSecretKey"],
                               new CardDataService<ApplicationDbContext, ApplicationUser>(Request.GetOwinContext().Get<ApplicationDbContext>())),
                           new CardDataService<ApplicationDbContext, ApplicationUser>(Request.GetOwinContext().Get<ApplicationDbContext>()),
                           new CustomerProvider(ConfigurationManager.AppSettings["StripeApiSecretKey"]),
                           new SubscriptionPlanDataService<ApplicationDbContext, ApplicationUser>(Request.GetOwinContext().Get<ApplicationDbContext>()),
                           new ChargeProvider(ConfigurationManager.AppSettings["StripeApiSecretKey"])));
            }
        }

        // GET: Notes
        public async Task<ActionResult> Index()
        {
            var userId = User.Identity.GetUserId();

            var userNotes =
                await
                    _db.Users.Where(u => u.Id == userId)
                        .Include(u => u.Notes)
                        .SelectMany(u => u.Notes)
                        .ToListAsync();

            return View(userNotes);
        }

        // GET: Notes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userId = User.Identity.GetUserId();
            ICollection<Note> userNotes = (
                await _db.Users.Where(u => u.Id == userId)
                    .Include(u => u.Notes).Select(u => u.Notes)
                    .FirstOrDefaultAsync());

            if (userNotes == null)
            {
                return HttpNotFound();
            }

            Note note = userNotes.FirstOrDefault(n => n.Id == id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // GET: Notes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Text,CreatedAt")] Note note)
        {
            if (ModelState.IsValid)
            {
                if (await UserHasEnoughSpace(User.Identity.GetUserId()))
                {
                    note.CreatedAt = DateTime.UtcNow;

                    // The note is added to the user object so the Foreign Key is saved too
                    var userId = User.Identity.GetUserId();
                    var user = await this._db.Users.Where(u => u.Id == userId).FirstOrDefaultAsync();
                    user.Notes.Add(note);

                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData.Add("flash", new FlashWarningViewModel("You can not add more notes, upgrade your subscription plan or delete some notes."));
                }
            }

            return View(note);
        }

        private async Task<bool> UserHasEnoughSpace(string userId)
        {
            var subscription = (await SubscriptionsFacade.UserActiveSubscriptionsAsync(userId)).FirstOrDefault();

            if (subscription == null)
            {
                return false;
            }

            var userNotes = await _db.Users.Where(u => u.Id == userId).Include(u => u.Notes).Select(u => u.Notes).CountAsync();

            return subscription.SubscriptionPlan.GetPropertyInt("MaxNotes") > userNotes;
        }

        // GET: Notes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!await NoteBelongToUser(User.Identity.GetUserId(), noteId: id.Value))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Note note = await _db.Notes.FindAsync(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Text,CreatedAt")] Note note)
        {
            if (ModelState.IsValid && await NoteBelongToUser(User.Identity.GetUserId(), note.Id))
            {
                _db.Entry(note).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!await NoteBelongToUser(User.Identity.GetUserId(), noteId: id.Value))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Note note = await _db.Notes.FindAsync(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (!await NoteBelongToUser(User.Identity.GetUserId(), noteId: id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Note note = await _db.Notes.FindAsync(id);
            _db.Notes.Remove(note);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        private async Task<bool> NoteBelongToUser(string userId, int noteId)
        {
            return await _db.Users.Where(u => u.Id == userId).Where(u => u.Notes.Any(n => n.Id == noteId)).AnyAsync();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyNote/Views/Notes/Create.cshtml
@model MyNote.Models.Note

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h2>Create Note</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Note" class="btn btn-primary btn-block" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyNote/Views/Notes/Delete.cshtml
@model MyNote.Models.Note

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h3>Are you sure you want to delete this Note?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Model.CreatedAt.ToShortDateString()
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "Index", "Notes", new { @class = "btn btn-default" })
        </div>
    }
</div>

MyNote/Views/Notes/Details.cshtml
@model MyNote.Models.Note

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyNote/Views/Notes/Edit.cshtml
@model MyNote.Models.Note

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h2>Edit Note</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.CreatedAt)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Note" class="btn btn-primary btn-block" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyNote/Views/Notes/Index.cshtml
@model IEnumerable<MyNote.Models.Note>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h2>My Notes</h2>

<div class="pull-right">
    <p>
        @Html.ActionLink("New Note", "Create", "Notes", new { @class = "btn btn-primary" })
    </p>
</div>

@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                Title
            </th>
            <th>
                Text
            </th>
            <th>
                Created
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
                <td>
                    @item.CreatedAt.ToShortDateString()
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) -
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) -
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}
else
{

    <h4 style="margin-top: 50px;">You haven't created any notes yet.</h4>
}